name: List files-Workflow-case 1

on: 
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Step for List Files
      run: ls -R
