name: Manully Trigger Workflow

on: 
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: echo msg
      run: echo "manually workflow trigger"
